# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:4.7-jdk8-alpine

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.44.3/pact-1.44.3-linux-x86_64.tar.gz
  - tar xzf pact-1.44.3-linux-x86_64.tar.gz


build:
  stage: build
  script: gradle build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

# https://gitlab.com/help/ci/examples/test-scala-application.md
test:
  stage: test
  script:
    - gradle check
    - pact/bin/pact-broker can-i-deploy --pacticipant="spark-app" --broker-base-url="https://norwegianlga.pact.dius.com.au/" -u=$PACTBROKER_USERNAME -p=$PACTBROKER_PASSWORD
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
